# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: main

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Azure Pipelines
    vmImage: 'vs2017-win2016'

  steps:
  - checkout: self
  - script: echo Hello, world!
    displayName: 'Run Script'
